In [3]:
import pandas as pd
import numpy as np
import matplotlib

In [ ]:
#RAW DATA EXTRACTION

In [4]:
df = pd.read_csv('online_retail_II_reduced.csv')

In [5]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,01-12-2009 07:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,01-12-2009 07:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,01-12-2009 07:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,04-12-2009 14:56,5.95,17151.0,United Kingdom
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,04-12-2009 15:11,1.25,16451.0,United Kingdom

In [ ]:
#RENAMING COLUMNS TO READABLE FORM

In [6]:
df.rename(columns={'Customer ID':'Customer_ID'})

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer_ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,01-12-2009 07:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,01-12-2009 07:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,01-12-2009 07:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,04-12-2009 14:56,5.95,17151.0,United Kingdom
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,04-12-2009 15:11,1.25,16451.0,United Kingdom

In [5]:
#CHECKING NULL VALUES

In [7]:
df.isnull().any()

Invoice        False
StockCode      False
Description     True
Quantity       False
InvoiceDate    False
Price          False
Customer ID     True
Country        False
dtype: bool

In [ ]:
#Removed Customer ID with null Values

In [8]:
df = df.dropna(subset=['Customer ID']) 
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,01-12-2009 07:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,01-12-2009 07:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,01-12-2009 07:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,04-12-2009 14:56,5.95,17151.0,United Kingdom
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,04-12-2009 15:11,1.25,16451.0,United Kingdom

In [9]:
df.isnull().any()

Invoice        False
StockCode      False
Description    False
Quantity       False
InvoiceDate    False
Price          False
Customer ID    False
Country        False
dtype: bool

In [ ]:
#REMOVING NEGATIVE VALUES

In [10]:
df = df[df['Quantity']>0]	#Negative Quantity Removed 
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,01-12-2009 07:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,01-12-2009 07:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,01-12-2009 07:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,04-12-2009 14:56,5.95,17151.0,United Kingdom
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,04-12-2009 15:11,1.25,16451.0,United Kingdom

In [11]:
df = df[df['Price']>0] #Negative Price Removed
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,01-12-2009 07:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,01-12-2009 07:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,01-12-2009 07:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,01-12-2009 07:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,04-12-2009 14:56,5.95,17151.0,United Kingdom
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,04-12-2009 14:56,5.45,17151.0,United Kingdom
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,04-12-2009 15:11,1.25,16451.0,United Kingdom

In [12]:
#CHANGING FORMATS

In [13]:
df.loc[:, 'InvoiceDate']=pd.to_datetime(df['InvoiceDate']) #Converted InvoiceDate to date fromat.
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-01-12 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-01-12 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-01-12 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,2009-04-12 14:56:00,5.95,17151.0,United Kingdom
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,2009-04-12 15:11:00,1.25,16451.0,United Kingdom

In [14]:
#AGAIN CHANGING TO ORIGINAL DATAFRAME

In [15]:
df=df.copy()
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-01-12 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-01-12 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-01-12 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,2009-04-12 14:56:00,5.95,17151.0,United Kingdom
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,2009-04-12 15:11:00,1.25,16451.0,United Kingdom

In [ ]:
#CREATING A MONETARY VALUE FOR RFM ANALYSIS (feature Engineering)

In [16]:
df['TotalAmount']=df['Quantity'] * df['Price'] #Created monetary value of the product for RFM analysis
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-01-12 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-01-12 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-01-12 07:45:00,1.25,13085.0,United Kingdom,30.0
...,...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,2009-04-12 14:56:00,5.95,17151.0,United Kingdom,35.7
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom,65.4
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom,65.4
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom,65.4
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,2009-04-12 15:11:00,1.25,16451.0,United Kingdom,15.0

In [ ]:
#FINAL DATA TYPE CHECK

In [17]:
df.dtypes

Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
TotalAmount    float64
dtype: object

In [19]:
print("Shape of the data", df.shape)
df

Shape of the data (8340, 9)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-01-12 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-01-12 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-01-12 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-01-12 07:45:00,1.25,13085.0,United Kingdom,30.0
...,...,...,...,...,...,...,...,...,...
11571,490310,21551,CERAMIC BIRDHOUSE BUTTERFLY LARGE,6,2009-04-12 14:56:00,5.95,17151.0,United Kingdom,35.7
11572,490310,21550,CERAMIC BIRDHOUSE CRESTED TIT LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom,65.4
11573,490310,21552,CERAMIC BIRDHOUSE BLACK ROSE LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom,65.4
11574,490310,21554,CERAMIC BIRDHOUSE RED ROOF LARGE,12,2009-04-12 14:56:00,5.45,17151.0,United Kingdom,65.4
11575,490311,21232,STRAWBERRY CERAMIC TRINKET BOX,12,2009-04-12 15:11:00,1.25,16451.0,United Kingdom,15.0

In [ ]:
#EXPORTING CLEANED DATA

In [ ]:
#df.to_excel("cleaned_data_phase_1.xlsx", index=False) #Imported the file to xlsx format